name: Сборка Crystal OS для Redmi 7A/8/8A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: 1. Максимальная зачистка места на диске
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean
        docker rmi $(docker images -q) 2>/dev/null || true
        df -h

    - name: 2. Настройка пакетов и окружения Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: 3. Инициализация исходников Crystal OS (Глубина 1)
      run: |
        git config --global user.name "CrystalDev"
        git config --global user.email "crystal_dev@crystal.com"
        mkdir android && cd android
        repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --depth=1
        
    - name: 4. Погнали локальные репозитории (Crystal OS Manifest)
      run: |
        cd android
        mkdir -p .repo/local_manifests
        cat <<EOF > .repo/local_manifests/crystal.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
          <project path="device/xiaomi/mi439" name="Pashamin/android_device_xiaomi_pine" remote="github" revision="lineage-18.1" />
          <project path="kernel/xiaomi/sdm439" name="Pashamin/android_kernel_xiaomi_sdm439" remote="github" revision="lineage-18.1" />
          <project path="vendor/xiaomi/mi439" name="Pashamin/android_vendor_xiaomi_pine" remote="github" revision="lineage-18.1" />
        </manifest>
        EOF

    - name: 5. Полная синхронизация репозиториев (Repo Sync)
      run: |
        cd android
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: 6. Запуск компиляции прошивки (Режим экономии)
      run: |
        cd android
        source build/envsetup.sh
        # ВНИМАНИЕ: Если менял имя конфигурации в дереве на crystal_pine, верни crystal_pine-userdebug
        lunch lineage_pine-userdebug
        export MINIMAL_APPS=true
        export WITH_SU=true
        mka bacon -j2

    - name: 7. Создание официального релиза и загрузка ZIP
      if: success()
      uses: ncipollo/release-action@v1
      with:
        artifacts: "android/out/target/product/pine/*.zip"
        tag: "v1.0-pine"
        name: "Crystal OS v1.0 для Redmi 7A (pine)"
        body: "Официальная сборка Crystal OS на базе Android 11. Скомпилировано автоматически через GitHub Actions."
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
